# Generated by Django 5.0.6 on 2024-06-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizattempt",
            name="correct_answers",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="incorrect_answers",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="quiz",
            field=models.JSONField(default=list),
        ),
    ]
